src/Entity/Help.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HelpRepository")
 * @UniqueEntity("link", message="Ce lien a déjà été publié")
 */
class Help
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Url(message="Ce lien n'est pas valide")
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=75)
     * @Assert\NotBlank
     * @Assert\Length(max=75, maxMessage="Format invalide ({{ limit }} caractères maximum)")
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="helps")
     * @ORM\JoinColumn(nullable=false)
     */
    private $publisher;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language", inversedBy="helps", cascade={"persist"})
     */
    private $language;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPublisher(): ?User
    {
        return $this->publisher;
    }

    public function setPublisher(?User $publisher): self
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): self
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Get the difference between the project creating time and now
     * @return String
     */
    public function getInterval()
    {
        $time_diff = date_diff($this->created_at, new \DateTime());

        $format = "Aujourd'hui";
        if ($time_diff->d == 1) {
            $format = "Hier";
        }
        if ($time_diff->d > 1) {
            $format = "Il y a %d jours";
        }
        if ($time_diff->m > 0) {
            $format = "Il y a %m mois";
        }
        if ($time_diff->y > 0) {
            $format = "Il y a %m ans";
        }
        return $time_diff->format($format);
    }
}

src/Form/Other/CodeblockType.php
<?php

namespace App\Form\Other;

use App\Entity\Language;
use App\Entity\Codeblock;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CodeblockType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration(null,"Ex. Code pour un preloader"))
            ->add('language', EntityType::class, $this->getConfiguration('Langage principal du jeu', null, [
                'class'  =>   Language::class
            ]))
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Codeblock::class,
        ]);
    }
}

src/Form/Other/DeadlineType.php
<?php

namespace App\Form\Other;

use App\Entity\Deadline;
use App\Form\ApplicationType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DeadlineType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('endAt', DateType::class,     $this->getConfiguration('Date finale',null, [ 'widget'   => 'single_text']))
            ->add('task',  TextareaType::class, $this->getConfiguration('Intitulé de la tâche','Ex. finir le projet, arreter de boire, etc.'))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Deadline::class,
            'allow_extra_fields' => true
        ]);
    }
}

src/Form/Other/GameType.php
<?php

namespace App\Form\Other;

use App\Entity\Game;
use App\Entity\Language;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GameType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',    TextType::class,   $this->getConfiguration('','Titre de votre jeu'))
            ->add('link',     UrlType::class,    $this->getConfiguration('','http://lien-du-jeux.com'))
            ->add('github',   UrlType::class,    $this->getConfiguration('','http://lien-github-du-jeux.com'))
            ->add('language', EntityType::class, $this->getConfiguration('Langage principal du jeu', null, [
                'class'  =>   Language::class
            ]))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Form/Other/ScheduleType.php
<?php

namespace App\Form\Other;

use App\Entity\Schedule;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ScheduleType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('beginAt',   DateTimeType::class, $this->getConfiguration('Date de début', null, ['widget'   => 'single_text']))
            ->add('endAt',     DateTimeType::class, $this->getConfiguration('Date de fin',   null, ['widget'   => 'single_text']))
            ->add('title',     TextareaType::class, $this->getConfiguration('Description', 'Ex. Aller à la piscine, coder sans les mains, etc.'))
            ->add('important', CheckboxType::class, $this->getConfiguration(' ',null,[
                'attr'       => array('class' => 'custom-control-input'),
                'label_attr' => array('class' => 'custom-control-label'),
                'required'   => false
            ]))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Schedule::class,
        ]);
    }
}

templates/other/calendar.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Planning{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('build/css/calendar.css') }}">
{% endblock %}

{% block body %}
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <span>Agenda</span>
    </p>
    <hr class="w-100">
    <div class="container-white shadow-small calendar-view">
        {% include '@Calendar/calendar.html' %}
    </div>
    <div class="d-none container-white shadow-small p-5 calendar-resp text-center bold">
        Agenda inaccessible sur tablette et mobile.
    </div>
    <div class="my-5 text-center">
        <a href="{{ path('schedule_all') }}" class="text-grey bhover" aria-label="Plannings">Voir tous les plannings</a>
    </div>
{% endblock %}

{% block modalTitle %}Modifier le planning{% endblock %}

{% block javascripts %}
    <script src="/fc-core.min.js"></script>
    <script src="/fc-interaction.min.js"></script>
    <script src="/fc-daygrid.min.js"></script>
    <script src="/fc-timegrid.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        var calendarEl = document.getElementById('calendar-holder');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            defaultView: 'timeGridWeek',
            height: "auto",
            nowIndicator: true,
            editable: true,
            selectable: true,
            allDaySlot: false,
            hiddenDays: [0,6],
            minTime: "08:00:00",
            maxTime: "19:00:00",
            plugins: ['interaction', 'dayGrid', 'timeGrid'],
            timeZone: 'Europe/Luxembourg',
            locale: 'fr',
            eventSources: [{
                url: "{{ path('fc_load_events') }}",
                method: "POST",
                extraParams: {
                    filters: JSON.stringify({})
                },
                failure: () => {
                    console.log('error fullcalendar');
                },
            }, ],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,addBtn',
            },
            footer: {
                center: 'prev,next'
            },
            buttonText: {
                today:    'Aujourd\'hui',
                month:    'Mois',
                week:     'Semaine',
                day:      'Jour',
                list:     'Liste'
            },
            customButtons: {
                addBtn: {
                    text: 'Ajouter',
                    click: function(){
                        $.ajax({
                            url: '/admin/schedule/new',
                            type: "POST",

                            success: function(response){
                                $('.modal-main').modal();
                                $('.modal-main').find('.modal-body').html(response.render);
                            }
                        });
                    }
                }
            },
            select: function(event) {
                $.ajax({
                    url: '/admin/schedule/createAjax',
                    data: {
                        start : event.startStr,
                        end : event.endStr
                    },
                    type: "POST",

                    success: function(response){
                        var test = {
                            id: response.id,
                            title: '',
                            start: event.startStr,
                            end: event.endStr,
                            backgroundColor: 'white',
                            classNames: 'shadow-small rounded p-2 schedule',
                            borderColor: 'rgba(0,0,0,.25)'
                        };
                        calendar.addEvent(test);
                    }
                });
            },
            eventDrop: function(event) {
                var startString = new Date(event.event.start.toUTCString());
                var endString   = new Date(event.event.end.toUTCString());
                var start = startString.toISOString().replace('T',' ').replace('Z','');
                var end   = endString.toISOString().replace('T',' ').replace('Z','');
                var id    = parseInt(event.event.id);

                $.ajax({
                    url: '/admin/schedule/move',
                    data: {
                        id : id,
                        start : start,
                        end : end
                    },
                    type: "POST",

                    success: function(response){
                    }
                });
            },
            eventResize: function(event) {
                var startString = new Date(event.event.start.toUTCString());
                var endString   = new Date(event.event.end.toUTCString());
                var start = startString.toISOString().replace('T',' ').replace('Z','');
                var end   = endString.toISOString().replace('T',' ').replace('Z','');
                var id    = parseInt(event.event.id);

                $.ajax({
                    url: '/admin/schedule/move',
                    data: {
                        id : id,
                        start : start,
                        end : end
                    },
                    type: "POST",

                    success: function(response){
                    }
                });
            },
            eventClick: function(event) {
                var id = parseInt(event.event.id);
                $.ajax({
                    url: '/admin/schedule/editAjax',
                    data: {
                        id : id
                    },
                    type: "POST",

                    success: function(response){
                        $('.modal-main').modal();
                        $('.modal-main').find('.modal-body').html(response.render);
                    }
                });
            }
        });
        calendar.render();
    });
</script>
{% endblock %}

templates/other/deadline.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Liste des deadlines{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('build/css/other.css') }}">
{% endblock %}

{% block body %}
    <h1>Liste des deadlines</h1>
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <span>Deadlines</span>
    </p>
    <hr>
    <div class="container-white shadow-small deadline-all">
    {% for udeadline in app.user.userDeadline|reverse %}
        {% set deadline = udeadline.deadline %}
        <div class="row no-gutters">
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 col-12">
                {{ deadline }}
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-6 text-right beforeDate">
                <span class="text-small">Avant le {{ deadline.endAt|date('d/m/Y') }}</span>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 col-6">
                <div class="flex align-center just-center h-100">
                {% if udeadline.validate %}
                    <i class="fas fa-check-circle text-red deadlineValidate"></i>
                {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% block modal %}{% endblock %}

templates/other/edit_skills.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Modifier mon compte{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('build/css/user/main.css') }}">
{% endblock %}

{% form_theme form _self %}

{% block body %}
    {{ template.checkMessage(form, "Les niveaux doivent être compris entre 0 et 3") }}
    <h1>Modifier les compétences</h1>
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <a href="{{ path('admin_all_users') }}">Tous les utilisateurs</a> &nbsp; / &nbsp;
        <span>Compétences de {{ user }}</span>
    </p>
    <hr>
    {{ form_start(form) }}
        {% for form in form.userSkills %}
            <div class="container-white shadow-small flex wrap just-between align-center mb-2">
                <div class="w-75 edit-skill-label">{{ user.userSkills[loop.index-1].skill.label }}</div>
                <div>{{ form_widget(form) }}</div>
            </div>
        {% endfor %}
        {{ template.confirm() }}
    {{ form_end(form) }}
{% endblock %}

{% block _edit_user_skills_userSkills_entry_widget %}
    <div class="flex just-around align-center">
        <div class="flex mr-3">
            <div class="circle-level rounded-circle pointer level-0 mr-2" id="0" style="height: 15px; width: 15px"></div>
            <div class="circle-level rounded-circle pointer level-1 mr-2" id="1" style="height: 15px; width: 15px"></div>
            <div class="circle-level rounded-circle pointer level-2 mr-2" id="2" style="height: 15px; width: 15px"></div>
            <div class="circle-level rounded-circle pointer level-3 mr-2" id="3" style="height: 15px; width: 15px"></div>
        </div>
        {{ form_widget(form.level, {'attr': {'class': 'level p-0 rounded-circle text-white border-0 shadow-none'}}) }}
    </div>
{% endblock %}

{% block modal %}{% endblock %}

{% block javascripts %}
{{ encore_entry_script_tags('js/skills') }}
{% endblock %}

templates/other/login.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="description" content="Plateforme en ligne pour les formateurs et apprenants de la formation Simplon.co - Développement Web et Web Mobile de Charleville-Mézières"/>
        <meta name="robots" content="noindex"/>
        <title>SimplonOnline - Se connecter</title>
        <link rel="icon" type="image/png" href="/img/favicon.png" />
        <link rel='stylesheet' href='/FontAwesome/css/all.min.css'/>
        <link rel="stylesheet" href="{{ asset('build/css/main/base.css') }}">
    </head>
    <body>
        <div class="flex just-center align-center w-100 vh-100">
            <div class="container-white flexc shadow-small text-center py-3" style="width: 300px; height: 450px">
                <div class="text-center">
                    <img src="img/logo.jpeg" class="w-50" alt="Logo de Simplon.co"></img>
                </div>
                <div class="flexc just-center align-center h-100">
                    {% if error %}
                    <div class="text-red m-2 p-2 w-75 border shadow-small bold">
                        Une erreur est survenue. <br>
                        {{ error.messageKey|trans(error.messageData, 'security') }}
                    </div>
                    {% endif %}
                    <form action="{{ path('account_login') }}" method="post" class="w-100 px-4">
                        <div class="form-group">
                            <label for="email">Adresse mail</label>
                            <input type="text" name="_username" id="email" class="form-control" placeholder="Adresse mail" value="{{ username }}" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Mot de passe</label>
                            {# <input type="password" name="_password" id="password" class="login-password" class="form-control" placeholder="Mot de passe" required> #}
                            <div class="input-group mb-3">
                                <input type="password" name="_password" id="password" class="form-control login-password" placeholder="Mot de passe" aria-label="Mot de passe" aria-describedby="see-pwd">
                                <div class="input-group-append bhover">
                                    <span class="input-group-text" id="see-pwd"><i class="far fa-eye text-small text-grey"></i></span>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="_target_path" value="{{ path('account_show') }}"/>
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Se connecter</button>
                        </div>
                    </form>
                </div>
                    <a href="{{ path('home') }}" class="text-small text-grey bhover" aria-label="Page d'accueil">Page d'accueil.</a>
            </div>
        </div>

        {{ encore_entry_script_tags('js/app') }}
        <script>
            $(document).on('click','#see-pwd', function(){
                if($("#password")[0].type == "password"){
                    $("#password").prop("type", "text");
                } else {
                    $("#password").prop("type", "password");
                }
            })
        </script>
    </body>
</html>

templates/other/show_notif.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Liens d'aide{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('build/css/project/main.css') }}">
{% endblock %}

{% block body %}
    {{ template.deleteConfirm('delete-all',path('account_delete_all_notif'), 'Toutes vos notifications seront supprimées')}}
    <div class="flex wrap just-between align-center">
        <h1>Vos notifications</h1>
        <i data-toggle="modal" data-target="#modal-delete-all" class="fal fa-times-circle icon-md pointer rhover"></i>
    </div>
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <span>Notifications</span>
    </p>
    <hr>
    <div class="container-white shadow-small">
        {% for unotif in app.user.notifReceived|reverse %}
            {% set notif = unotif.notification %}
            <div class="flex wrap align-center just-between my-n1">
                <div class="flex wrap align-center w-66 notif-content">
                    {% if unotif.seen %}
                    <div class="status-white mr-1"></div>
                    {% else %}
                    <div class="status-red mr-1"></div>
                    {% endif %}
                    {{ notif.title }}
                    <span class="text-small text-grey ml-2">
                        par {{ notif.sender.firstname|capitalize }} {{ notif.sender.lastname|slice(0,1)|upper }}.
                    </span>
                </div>
                <div class="notif-info">
                    <span class="text-small text-grey">{{ notif.interval }}</span>
                    {% if notif.type == 1 or notif.type == 2 %}
                    <a href="{{ path('project_show',{'slug': notif.target}) }}?seen={{unotif.id}}" class="btn text-grey bhover" aria-label="Voir le projet"><i class="far fa-arrow-circle-right"></i></a>
                    {% elseif notif.type == 3 %}
                    <a href="{{ path('account_show') }}?seen={{unotif.id}}" class="btn text-grey bhover" aria-label="Compétences"><i class="far fa-arrow-circle-right"></i></a>
                    {% else %}
                    <a href="{{ path('file_user_show') }}?seen={{unotif.id}}" class="btn text-grey bhover" aria-label="Fichiers"><i class="far fa-arrow-circle-right"></i></a>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <div class="text-center py-2">
                <i class="fal fa-times-hexagon icon-sm"></i><br>
                <span class="bold">Aucune notification</span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block modal %}{% endblock %}