src/Entity/Files.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilesRepository")
 */
class Files
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez choisir un fichier")
     * @Assert\File(
     *     maxSize = "5M",
     *     maxSizeMessage = "Taille autorisée : {{ limit }} {{ suffix }}",
     *     mimeTypes = {
     *         "image/*",
     *         "application/*",
     *         "text/*",
     *     },
     *     mimeTypesMessage = "Le fichier n'est pas valide"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=60)
     * @Assert\NotBlank(message="Veuillez renseigner un titre")
     * @Assert\Length(max=60, maxMessage="Format invalide ({{ limit }} caractères maximum)")
     */
    private $title;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserFiles", mappedBy="files", cascade={"persist","remove"})
     */
    private $userFiles;

    public function __construct()
    {
        $this->userFiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|UserFiles[]
     */
    public function getUserFiles(): Collection
    {
        return $this->userFiles;
    }

    public function addUserFile(UserFiles $userFile): self
    {
        if (!$this->userFiles->contains($userFile)) {
            $this->userFiles[] = $userFile;
            $userFile->setFiles($this);
        }

        return $this;
    }

    public function removeUserFile(UserFiles $userFile): self
    {
        if ($this->userFiles->contains($userFile)) {
            $this->userFiles->removeElement($userFile);
            // set the owning side to null (unless already changed)
            if ($userFile->getFiles() === $this) {
                $userFile->setFiles(null);
            }
        }

        return $this;
    }


}

src/Entity/UserFiles.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserFilesRepository")
 */
class UserFiles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="userFiles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $receiver;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Files", inversedBy="userFiles", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $files;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="senderFiles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_send;

    /**
     * @ORM\Column(type="boolean")
     */
    private $seen;


    public function __construct()
    {
        $this->date_send = new \DateTime();
        $this->seen      = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReceiver(): ?User
    {
        return $this->receiver;
    }

    public function setReceiver(?User $receiver): self
    {
        $this->receiver = $receiver;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getDateSend(): ?\DateTimeInterface
    {
        return $this->date_send;
    }

    public function setDateSend(\DateTimeInterface $date_send): self
    {
        $this->date_send = $date_send;

        return $this;
    }

    public function getSeen(): ?bool
    {
        return $this->seen;
    }

    public function setSeen(bool $seen): self
    {
        $this->seen = $seen;

        return $this;
    }

    public function getFiles(): ?Files
    {
        return $this->files;
    }

    public function setFiles(?Files $files): self
    {
        $this->files = $files;

        return $this;
    }
}

src/Form/File/EditUserFilesType.php
<?php

namespace App\Form\File;

use App\Entity\User;
use App\Entity\UserFiles;
use App\Form\ApplicationType;
use App\Form\File\UserFilesType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EditUserFilesType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('userFiles', UserFilesType::class, [
                'data_class' => UserFiles::class
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Form/File/FilesAdminType.php
<?php

namespace App\Form\File;

use App\Entity\User;
use App\Entity\Files;
use App\Form\ApplicationType;
use App\Repository\UserRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class FilesAdminType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',    TextType::class,$this->getConfiguration('Titre de votre document','Max. 50 caractères'))
            ->add('name',     FileType::class,[
                'data_class'    => null,
                'label'         => 'Taille maximum: 5mo'
            ])
            ->add('receiver', EntityType::class, [
                'class'         => User::class,
                'label'         => 'Destinataire',
                'multiple'      => true,
                'mapped'        => false,
                'query_builder' => function(UserRepository $rep) {
                    return $rep->findCurrentPromoType();
                }

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Files::class,
        ]);
    }
}

src/Form/File/FilesType.php
<?php

namespace App\Form\File;

use App\Entity\User;
use App\Entity\Files;
use App\Form\ApplicationType;
use App\Repository\UserRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class FilesType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',      FileType::class,['data_class' => null])
            ->add('title',     TextType::class,$this->getConfiguration('Titre de votre document','Max. 50 caractères'))
            ->add('receiver',  EntityType::class, [
                'class'         => User::class,
                'label'         => 'Destinataire',
                'multiple'      => true,
                'mapped'        => false,
                'query_builder' => function(UserRepository $rep) {
                    return $rep->getAllUserRoleByCurrentPromo();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Files::class,
        ]);
    }
}

src/Controller/FileController.php
<?php

namespace App\Controller;

use App\Entity\Files;
use App\Entity\UserFiles;
use App\Entity\UserNotif;
use App\Entity\Notification;
use App\Form\File\FilesType;
use App\Form\File\FilesAdminType;
use App\Repository\UserRepository;
use App\Repository\UserFilesRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * @Route("/fichiers", name="file_")
 */
class FileController extends AbstractController
{
    /**
     * File section
     *  - Show the files received
     *  - Show the files sent
     *  - Form to send a file to the mediators by the current user
     *  - Form to send a file to an user by the mediators
     * @Route("/index", name="user_show")
     * @param Request        $request
     * @param ObjectManager  $manager
     * @param UserRepository $rep
     * @return Response
     */
    public function showFileUser(Request $request, ObjectManager $manager, UserRepository $rep)
    {
        if($request->query->get('seen') != null){
            $unotif = $this->getDoctrine()->getRepository(UserNotif::class)->find($request->query->get('seen'));
            if($unotif != null){
                $unotif->setSeen(true);
                $manager->persist($unotif);
                $manager->flush();
            }
        }

        $user = $this->getUser();

        $access = ($this->isGranted('ROLE_FORMER') || $this->isGranted('ROLE_MEDIATOR'));
        $file = new Files();
        $form = $access ? $this->createForm(FilesAdminType::class, $file) : $this->createForm(FilesType::class, $file);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $filename = $this->moveFile($form->get('name')->getData(),$form->get('title')->getData(), $rep);
            $file->setName($filename);

            // New notification
            $notif = $user->createSenderNotif(Notification::FILE);
            $manager->persist($user);

            if($access){
                $data = $request->request->get('files_admin');
                foreach($data['receiver'] as $receiver_id){
                    $receiver = $rep->find($receiver_id);
                    $receiver->createUserFile($this->getUser(), $file);
                    $receiver->createUserNotif($notif);
                    $manager->persist($receiver);
                }
            } else {
                $data = $request->request->get('files');
                foreach($data['receiver'] as $sup_user_id){
                    $sup_user = $rep->find($sup_user_id);
                    $sup_user->createUserFile($this->getUser(), $file);
                    $sup_user->createUserNotif($notif);
                    $manager->persist($sup_user);
                }
            }
            $manager->flush();

            $this->addFlash(
                'success',
                'Le fichier a bien été envoyé.'
            );
        }

        $sending = $this->getDoctrine()->getRepository(UserFiles::class)->findBy([
            'sender' => $user
        ]);

        return $this->render('file/show_files.html.twig', [
            'user'    => $user,
            'form'    => $form->createView(),
            'access'  => $access,
            'sending' => $sending
        ]);
    }

    /**
     * Change seen false to a specific file )
     * @Route("/{id}/changer_status", name="edit_status")
     * @param FileUser      $file
     * @param ObjectManager $manager
     * @return Response
     */
    public function editStatusFileUser(UserFiles $ufile, ObjectManager $manager)
    {
        if($this->getUser() != $ufile->getSender() && $this->getUser() != $ufile->getReceiver()){
            throw new AccessDeniedException();
        }

        $ufile->setSeen(true);
        $manager->persist($ufile);
        $manager->flush();

        return new JsonResponse();
    }

    /**
     * Remove a specific file received by the current user
     * @Route("/{id}/enlever", name="received_remove")
     * @param Files               $file
     * @param ObjectManager       $manager
     * @param UserFilesRepository $rep
     * @return Response
     */
    public function removeReceivedFile(Files $file, ObjectManager $manager, UserFilesRepository $rep)
    {
        $ufile = $rep->findOneBy([
            'receiver' => $this->getUser(),
            'files'    => $file
        ]);

        $manager->remove($ufile);
        $manager->flush();

        $checkFile = $rep->findBy(['files' => $file]);
        if($checkFile == null && $file != null){
            $this->removeFile($file->getName());
            $manager->remove($file);
        }
        $manager->flush();

        return new JsonResponse();
    }

    /**
     * Delete all current user's files (sent)
     * @Route("/tout_supprimer", name="delete_all")
     * @param ObjectManager $manager
     * @return Response
     */
    public function deleteAllFilesUser(ObjectManager $manager)
    {
        if(!$this->isGranted('ROLE_FORMER') && !$this->isGranted('ROLE_MEDIATEUR') && $this->getUser() == null){
            throw new AccessDeniedException();
        }

        $user = $this->getUser();
        foreach($user->getSenderFiles() as $ufile){
            $file = $ufile->getFiles();
            if($file != null){
                $this->removeFile($file->getName());
            }
            $manager->remove($ufile);
        }
        $manager->flush();

        $this->addFlash(
            'success',
            'Les fichiers ont bien été supprimés.'
        );

        return $this->redirectToRoute('file_user_show');
    }

    /**
     * Delete a file by a sender only
     * @Route("/{id}/supprimer", name="delete")
     * @param Files         $file
     * @param ObjectManager $manager
     * @return Response
     */
    public function deleteFileUser(Files $file, ObjectManager $manager)
    {
        if(!$this->isGranted('ROLE_FORMER') && !$this->isGranted('ROLE_MEDIATEUR') && $this->getUser() == null){
            throw new AccessDeniedException();
        }

        $rep = $this->getDoctrine()->getRepository(UserFiles::class);
        $this->removeFile($file->getName());

        $ufiles = $rep->findBy([
            'sender' => $this->getUser(),
            'files' => $file
        ]);
        foreach($ufiles as $ufile){
            $manager->remove($ufile);
        }
        $manager->remove($file);
        $manager->flush();

        $this->addFlash(
            'success',
            'Le fichier a bien été supprimé.'
        );

        return $this->redirectToRoute('file_user_show');
    }

    /**
     * Download a specific file
     * @Route("/{id}", name="download")
     * @param Files $file
     * @return JsonResponse
     */
    public function downloadFile(Files $file)
    {
        try {
            if (!$file) {
                $array = array (
                    'status' => 0,
                    'message' => 'File does not exist'
                );
                $response = new JsonResponse ( $array, 200 );

                return $response;
            }
            $file_with_path = $this->getParameter('file_directory') . "/" . $file->getName();
            $response = new BinaryFileResponse ( $file_with_path );
            $response->headers->set ( 'Content-Type', 'text/plain' );
            $response->setContentDisposition ( ResponseHeaderBag::DISPOSITION_ATTACHMENT, $file->getTitle() );

            return $response;
        } catch ( Exception $e ) {
            $array = array (
                'status'  => 0,
                'message' => 'Download error'
            );
            $response = new JsonResponse ( $array, 400 );

            return $response;
        }
    }

    /**
     * Move the file upload to the file directory
     * @param string         $name  the upload file name
     * @param string         $title the title given by the user
     * @param UserRepository $rep
     * @return string
     */
    public function moveFile($name, $title, $rep)
    {
        $file = $name;
        $fileName = "";
        if($file != NULL)
        {
            $lastUserFile = $rep->findOneBy([], ['id' => 'desc']);
            $id = $lastUserFile !== null ? $lastUserFile->getId()+1 : 1;
            $fileName = str_replace(" ","-",$title);
            $fileName .= $id.'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('file_directory'),
                $fileName
            );
        }
        return $fileName;
    }

    /**
     * Remove the file from the directory
     * @param string $filename the file name
     * @return void
     */
    public function removeFile($filename)
    {
        $file = $this->getParameter('file_directory') . "/" . $filename;
        $filesystem = new Filesystem();
        $filesystem->remove($file);
    }
}

templates/file/_form.html.twig
{% import 'macro.html.twig' as template %}

<div class="container-white h-100 form-files">
    <p class="bold">Envoyer un fichier</p>
    <div>
        {{ form_start(form) }}
            {{ form_errors(form.name) }}
            {{ form_label(form.title) }}
            {{ form_widget(form.title, { 'attr': { 'maxlength' : 60 } }) }}
            <hr>
            {{ form_label(form.receiver) }}
            {{ form_widget(form.receiver, {'attr': {
                'class': 'files-selected selectpicker',
                'title': 'Choisir les utilisateurs',
                'data-live-search': 'true',
                'multiple': '',
                'data-selected-text-format': 'count > 2',
                'data-style': 'bg-grey',
                'data-size': '6'
            }}) }}
            <hr>
            {{ form_widget(form.name) }}
            {{ template.confirm()}}
        {{ form_end(form) }}
    </div>
</div>

templates/file/_received.html.twig
<div class="received-files mr-2">
    <input type="hidden" class="file-counter" data-counter="{{user.userFiles|length}}">
    {% for ufiles in user.userFiles | reverse %}
        {% set file = ufiles.files %}
        <div>
            <div class="container-white flex just-center align-center p-3 mb-2">
                {% if ufiles.seen == true %}
                <div class="file-state rounded-circle mr-2 bg-white"></div>
                {% else %}
                <div class="file-state rounded-circle mr-2 bg-red ufile-{{ufiles.id}}"></div>
                {% endif %}
                <div class="file-info">
                    <p class="bold">{{ file.title }}</p>
                    <p class="text-small">
                        <em>Envoyé
                        {% if ufiles.sender != null %}
                        par {{ ufiles.sender.firstname }} {{ ufiles.sender.lastname | upper }}
                        {% endif %}
                        le {{ ufiles.dateSend | date('d/m/Y à H:i') }}</em>
                    </p>
                </div>
                <div class="subnav position-relative text-center px-1 text-greyl">
                    <i class="fas fa-ellipsis-v rhover"></i>
                    <div class="subnav-tooltip position-absolute text-center text-small shadow-small bg-white bold p-1 tooltip-file{% if ufiles.seen == false %}-important{% endif %}">
                        <a href="{{ path('file_download',{'id': file.id}) }}" class="subnav-link rhover" aria-label="Télécharger">Télécharger</a><br>
                        {% if ufiles.seen == false %}
                        <a data-url="{{ path('file_edit_status',{'id': ufiles.id}) }}" data-target="ufile-{{ufiles.id}}" class="subnav-link rhover remove-important">Marquer comme vu</a><br>
                        {% endif %}
                        <a data-url="{{ path('file_received_remove',{'id': file.id}) }}" class="subnav-link text-red bold pointer remove-file">Supprimer</a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <span class="bold">Mes fichiers reçus</span>
    <div class="flex just-center align-center text-center text-large text-grey h-100">
        <p>
            <i class="fal fa-folder-open text-xlarge"></i><br>
            Aucun fichier reçu
        </p>
    </div>
    {% endfor %}
    <div class="no-files h-100">
        <div class="flex just-center align-center text-center text-large text-grey h-100">
            <p>
                <i class="fal fa-folder-open text-xlarge"></i><br>
                Aucun fichier reçu
            </p>
        </div>
    </div>
</div>

templates/file/_sent.html.twig
{% import 'macro.html.twig' as template %}

<div class="flex just-between align-baseline pt-1">
    <span class="bold ml-1">Mes fichiers envoyés</span>
    {% if sending is not empty %}
        <div class="rhover text-small ml-2" data-toggle="modal" data-target="#modal-delete-all">
            Tout supprimer <i class="fal fa-times-circle text-red"></i>
        </div>
    {% endif %}
</div>

{% for usend in sending | reverse %}
    {% set file = usend.files %}
    {{ template.deleteConfirm(file.id, path('file_delete',{'id': file.id}), "Ce fichier sera supprimé définitivement et ne sera plus accessible par les autres utilisateurs.") }}

    <div class="container-white flex just-center align-center p-3 my-2">
        <div class="file-info">
            <p class="bold">{{ file.title }}</p>
            <p class="text-small">
                <em>Envoyé
                {% if usend.sender != null %}
                à {{ usend.receiver.firstname }} {{ usend.receiver.lastname | upper }}
                {% endif %}
                le {{ usend.dateSend | date('d/m/Y à H:i') }}</em>
            </p>
        </div>
        <div>
            <div class="subnav position-relative text-center rhover px-1 text-grey">
                <i class="fas fa-ellipsis-v"></i>
                <div class="subnav-tooltip position-absolute text-center text-small shadow-small bg-white bold p-1">
                    <a href="{{ path('file_download',{'id': file.id}) }}" class="subnav-link rhover" aria-label="Télécharger">Télécharger</a><br>
                    <a class="subnav-link text-red" data-toggle="modal" data-target="#modal-{{file.id}}">Supprimer</a>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="flex just-center align-center text-center text-large text-grey h-100 my-5">
        <p>
            <i class="fal fa-folder-open text-xlarge"></i><br>
            Aucun fichier envoyé
        </p>
    </div>
{% endfor %}

{{ template.deleteConfirm('delete-all',path('file_delete_all'),'Ces fichiers seront supprimés définitivement et ne seront plus accessibles par les autres utilisateurs.') }}

templates/file/show_files.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Gestion des fichiers{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('build/css/libraries/bootstrap-select.css') }}">
<link rel="stylesheet" href="{{ asset('build/css/file.css') }}">
{% endblock %}

{% block body %}
    {{ template.checkMessage(form)}}
    <h1>Gestion des fichiers</h1>
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <span>Mes fichiers</span>
    </p>
    <hr>
    <div class="container-grey mt-2 flex show-files">
        {{ include('file/_received.html.twig', {'user':user}) }}
        {{ include('file/_form.html.twig', {'form':form}) }}
    </div>
    <hr>
    <div class="container-grey mt-2">
        {{ include('file/_sent.html.twig', {'sending':sending}) }}
    </div>
{% endblock %}

{% block modal %}{% endblock %}

{% block libraries %}
{{ encore_entry_script_tags('js/libraries/bootstrap-select') }}
{% endblock %}