src/Entity/Game.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max=255, maxMessage="Format invalide ({{ limit }} caractères maximum)")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *    message = "The url '{{ value }}' is not a valid url",
     * )
     */
    private $link;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(
     *    message = "The url '{{ value }}' is not a valid url",
     * )
     */
    private $github;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="games")
     * @ORM\JoinColumn(nullable=false)
     */
    private $publisher;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language", inversedBy="games")
     */
    private $language;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vote", mappedBy="game", orphanRemoval=true)
     */
    private $vote;

    public function __construct(User $user)
    {
        $this->publishedAt = new \DateTime();
        $this->publisher   = $user;
        $this->vote = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(?string $github): self
    {
        $this->github = $github;

        return $this;
    }

    public function getPublisher(): ?User
    {
        return $this->publisher;
    }

    public function setPublisher(?User $publisher): self
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): self
    {
        $this->language = $language;

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVote(): Collection
    {
        return $this->vote;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->vote->contains($vote)) {
            $this->vote[] = $vote;
            $vote->setGame($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->vote->contains($vote)) {
            $this->vote->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getGame() === $this) {
                $vote->setGame(null);
            }
        }

        return $this;
    }

    /**
     * Get a specific vote's like number
     * @return boolean
     */
    public function getVoteLikes()
    {
        $countLike = 0;
        foreach($this->vote as $vote){
            if($vote->getLikeType()){
                $countLike++;
            }
        }
        return $countLike;
    }

    /**
     * Get a specific vote's dislike number
     * @return boolean
     */
    public function getVoteDislikes()
    {
        $countDislike = 0;
        foreach($this->vote as $vote){
            if(!$vote->getLikeType()){
                $countDislike++;
            }
        }
        return $countDislike;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Language;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GameType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',    TextType::class,   $this->getConfiguration('','Titre de votre jeu'))
            ->add('link',     UrlType::class,    $this->getConfiguration('','http://lien-du-jeux.com'))
            ->add('github',   UrlType::class,    $this->getConfiguration('','http://lien-github-du-jeux.com'))
            ->add('language', EntityType::class, $this->getConfiguration('Langage principal du jeu', null, [
                'class'  =>   Language::class
            ]))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Form/Other/GameType.php
<?php

namespace App\Form\Other;

use App\Entity\Game;
use App\Entity\Language;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GameType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',    TextType::class,   $this->getConfiguration('','Titre de votre jeu'))
            ->add('link',     UrlType::class,    $this->getConfiguration('','http://lien-du-jeux.com'))
            ->add('github',   UrlType::class,    $this->getConfiguration('','http://lien-github-du-jeux.com'))
            ->add('language', EntityType::class, $this->getConfiguration('Langage principal du jeu', null, [
                'class'  =>   Language::class
            ]))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

templates/game/all.html.twig
{% extends 'base.html.twig' %}

{% import 'macro.html.twig' as template %}

{% block title %}Liste des jeux créés par les apprenants{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('build/css/other.css') }}">
{% endblock %}

{% block body %}
    <div class="flex just-between align-center games-title">
        <h1 class="w-75">Liste des jeux créés par les apprenants</h1>
        {{ template.add() }}
    </div>
    <p class="text-small main-breadcrumb">
        <a href="{{ path('account_show') }}">Accueil</a> &nbsp; / &nbsp;
        <span>Jeux</span>
    </p>
    <hr>
    <div class="flex wrap just-center align-content-stretch games">
    {% for game in pagination.data %}
        {% if is_granted('ROLE_FORMER') or is_granted('ROLE_MEDIATEUR') or game.publisher == app.user %}
        {{ template.deleteConfirm(game.id,path('user_game_delete',{'id': game.id,'page': page})) }}
        {{ template.modal("modal-edit-"~game.id) }}
        {% endif %}
        <div class="container-white shadow-small flexc m-1 h-auto games-container" style="width: 32%">
            <a href="{{ game.link }}" class="bold game-title" target="_blank" rel="noreferrer" aria-label="Lien">
                {{ game }}
            </a>
            <p class="text-grey text-small">
                Publié par {{ game.publisher }} le {{ game.publishedAt | date('d/m/Y') }}
            </p>
            <p class="flex align-center">
                {% if game.language is not null %}
                <span class="badge badge-pill badge-danger my-1">{{ game.language }}</span>
                {% endif %}
                {% if game.github is not null %}
                <a href="{{ game.github }}" class="text-small text-grey ml-2 mr-1" target="_blank" rel="noreferrer" aria-label="Github">
                    <i class="fal fa-code-branch"></i>
                </a>
                {% endif %}
                <a href="{{ game.link }}" class="text-small text-grey mx-1" target="_blank" rel="noreferrer" aria-label="Lien">
                    <i class="fal fa-link"></i>
                </a>
            </p>
            <div class="mt-auto flex just-between align-center text-grey text-small" style="bottom: 0; right: 0">
                {% if is_granted('ROLE_FORMER') or is_granted('ROLE_MEDIATEUR') or game.publisher == app.user %}
                    <p class="mt-1">
                        <span class="mx-1">
                            <i class="fal fa-times-circle rhover" data-toggle="modal" data-target="#modal-{{game.id}}"></i>
                        </span>
                        <span class="mx-1">
                            <i class="fal fa-pen bhover game-edit" data-toggle="modal" data-target="#modal-edit-{{game.id}}" data-url="{{ path('user_game_edit',{'id': game.id}) }}"></i>
                        </span>
                    </p>
                {% endif %}
                <p class="ml-auto">
                    <span class="mx-1 pointer vote {% if app.user.like(game) %}text-like{% endif %}" data-content="like" data-url="{{ path('user_game_vote', {'id': game.id}) }}">
                        <i class="fal fa-thumbs-up"></i>
                        <span class="count">{{ game.voteLikes }}</span>
                    </span>
                    <span class="mx-1 pointer vote {% if app.user.dislike(game) %}text-dislike{% endif %}" data-content="dislike" data-url="{{ path('user_game_vote', {'id': game.id}) }}">
                        <i class="fal fa-thumbs-down"></i>
                        <span class="count">{{ game.voteDislikes }}</span>
                    </span>
                </p>
            </div>
        </div>
    {% else %}
        <span class="bold">Aucun jeu pour le moment</span>
    {% endfor %}
    </div>

    {{ pagination.render(pagination.data is empty) }}
{% endblock %}

{% block modalTitle %}Ajouter un jeu{% endblock %}
{% block modalBody %}
    {{ form_start(form) }}
    <div class="my-2">
        {{ form_widget(form.title) }}
    </div>
    <hr>
    <div class="my-2">
        {{ form_widget(form.link) }}
    </div>
    <hr>
    <div class="my-2">
        {{ form_widget(form.github) }}
    </div>
    <hr>
    <div class="my-2">
        {{ form_widget(form.language) }}
    </div>
    <hr>
    {{ template.confirm() }}
    {{ form_end(form) }}
{% endblock %}

templates/game/edit.html.twig
{% import 'macro.html.twig' as template %}

<div class="flex just-between align-center">
    <h2>Modifier le jeu</h2>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<hr>
<div class="modal-main">
    {{ form_start(form, {'action': path('user_game_edit',{'id':game.id})}) }}
        <div class="my-2">
            {{ form_widget(form.title) }}
        </div>
        <hr>
        <div class="my-2">
            {{ form_widget(form.link) }}
        </div>
        <hr>
        <div class="my-2">
            {{ form_widget(form.github) }}
        </div>
        <hr>
        <div class="my-2">
            {{ form_widget(form.language) }}
        </div>
        <hr>
        {{ template.confirm() }}
    {{ form_end(form) }}
</div>